// Objective-C API for talking to github.com/DimitarPetrov/stegify/steg Go package.
//   gobind -lang=objc github.com/DimitarPetrov/stegify/steg
//
// File is generated by gobind. Do not edit.

#ifndef __Steg_H__
#define __Steg_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


// skipped function Decode with unsupported parameter or return types


/**
 * DecodeByFileNames performs steganography decoding of data previously encoded by the Encode function.
The data is decoded from file carrier and it is saved in separate new file
 */
FOUNDATION_EXPORT BOOL StegDecodeByFileNames(NSString* _Nullable carrierFileName, NSString* _Nullable newFileName, NSError* _Nullable* _Nullable error);

// skipped function Encode with unsupported parameter or return types


/**
 * EncodeByFileNames performs steganography encoding of data file in carrier file
and saves the steganography encoded product in new file.
 */
FOUNDATION_EXPORT BOOL StegEncodeByFileNames(NSString* _Nullable carrierFileName, NSString* _Nullable dataFileName, NSString* _Nullable resultFileName, NSError* _Nullable* _Nullable error);

#endif
