
// Objective-C API for talking to the following Go packages
//
//	github.com/DimitarPetrov/stegify/steg
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Steg_FRAMEWORK_H__
#define __Steg_FRAMEWORK_H__

#include "Steg.objc.h"
#include "Universe.objc.h"

#endif
